package me.jishuna.customentitylib.model;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import me.jishuna.customentitylib.resourcepack.ResourcePack;
import me.jishuna.customentitylib.resourcepack.model.AtlasSource;
import me.jishuna.customentitylib.resourcepack.model.ItemModel;

public class ModelManager {
    private final Map<String, EntityModel> models = new HashMap<>();

    public void registerModel(EntityModel model) {
        this.models.put(model.getName(), model);
    }

    public EntityModel getModel(String name) {
        return this.models.get(name);
    }

    public void generateResourcePack(File target) {
        ResourcePack pack = ResourcePack.fromFile(target);
        pack.getPackMeta().packData.packFormat = 12;
        pack.getPackMeta().packData.description = "Autogenerated resource pack";

        AtlasSource source = new AtlasSource("directory", "models", "models/");
        pack.getAtlas("blocks.json").sources.add(source);

        ItemModel model = pack.getItemModel("minecraft", "item/leather_horse_armor.json", true);
        model.textures.put("layer0", "minecraft:item/leather_horse_armor");
        model.parent = "item/generated";

        this.models.values().forEach(m -> m.write(pack));
        pack.close();
    }
}
